delete classroom api created
jako2889/The-Final-Order pull request #10
Opened 2020-04-23 18:37 UTC by jako2889

Fik lige lavet den her 💯

2020-04-23 18:42 UTC, magn3506 requested changes

2020-04-23 18:42 UTC, magn3506 commented on private/api/classrooms/delete-classroom.php
> +            echo "$deletedRows rows where deleted. Something went wrong. Maybe the lecture 'id' provided does not exist";
Change comment. So it matches.

2020-04-23 18:50 UTC, jako2889 reviewed
Changed echo comment

2020-04-24 08:08 UTC, magn3506 approved these changes

2020-04-24 08:08 UTC, merged